spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d88kb06l51nc73fjcsr0-a.singapore-postgres.render.com/cvd_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cvd_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.jpa.hibernate.ddl-auto=update

ml.service.url=https://cvd-ml-1tco.onrender.com
ml.api.key=${CVD_ML_API_KEY}
jwt.secret=${CVD_JWT_SECRET}
