spring.datasource.url=jdbc:postgresql://dpg-d88kb06l51nc73fjcsr0-a.singapore-postgres.render.com/cvd_db
spring.datasource.username=cvd_db_user
spring.datasource.password=m98euhDfWY2J76ymo2LkJtJU7gSR0bGo
spring.jpa.hibernate.ddl-auto=update

ml.service.url=https://cvd-ml-1tco.onrender.com
ml.api.key=${CVD_ML_API_KEY}
jwt.secret=${CVD_JWT_SECRET}
